# Generated by Django 2.2.10 on 2021-08-19 07:10

from django.db import migrations, models
import django_matplotlib.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompositeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('function', models.CharField(max_length=50, verbose_name='Функция')),
                ('interval', models.IntegerField(verbose_name='Интервал t,дней')),
                ('processing_date', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата обработки')),
                ('function_plot', django_matplotlib.fields.MatplotlibFigureField()),
            ],
        ),
    ]
